# orthogonal NMF

In [6]:
import numpy as np
import scipy as sp

In [375]:
r = 10
c = 10
l = 2
X = np.array([i+1 for i in range(r*c)[::-1]]).reshape(r,c)
U,s,V = np.linalg.svd(X)
E = np.pad(np.diag(s),((0,U.shape[1] - len(E)),(0,0)))
print(U.shape,E.shape,V.shape)
print(X)
# print(U.dot(E).dot(V.T))

(10, 10) (10, 10) (10, 10)
[[100  99  98  97  96  95  94  93  92  91]
 [ 90  89  88  87  86  85  84  83  82  81]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 70  69  68  67  66  65  64  63  62  61]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 50  49  48  47  46  45  44  43  42  41]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 30  29  28  27  26  25  24  23  22  21]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 10   9   8   7   6   5   4   3   2   1]]


In [376]:
print(s)

[5.81505563e+02 1.41873105e+01 3.41801612e-14 9.75747915e-15
 7.53192786e-15 5.38105033e-15 3.24735195e-15 6.10581788e-16
 1.55239728e-16 3.21107193e-17]


In [377]:
A = np.abs(U[:,:l])*np.sqrt(s[0])
S = V[:l]
print(X.shape,A.shape,S.shape)

(10, 10) (10, 2) (2, 10)


In [381]:
# print(A.dot(S))
for _ in range(10000):
        S = np.multiply(S, 
                        np.divide(A.T.dot(X), 
                                  A.T.dot(A).dot(S)))
#     A = np.multiply(A, 
#                     np.divide(X.dot(S.T),
#                               A.dot(S).dot(X.T).dot(A)))
        A = np.multiply(A, 
                        np.divide(X.dot(S.T),
                                  A.dot(A.T).dot(X).dot(S.T)))
print(A.dot(S)[:,0])

[74485.17393857 66693.30702112 59149.79012068 52059.03911654
 44969.12283439 37879.3510542  30261.10944839 21801.65931694
 13342.20918477  4882.75905261]


In [365]:
np.add(A,0)

array([[ 6.47752754e-001,  1.62344221e-003],
       [ 5.76150799e-001,  9.65511817e-003],
       [ 4.87552272e-001,  5.40087154e-002],
       [ 3.67486651e-001,  1.65613545e-001],
       [ 2.20632436e-001,  3.34441366e-001],
       [ 8.60055677e-002,  4.77153490e-001],
       [ 2.26215541e-004,  5.15729965e-001],
       [ 8.12233866e-014,  3.71916172e-001],
       [ 1.16944093e-035,  2.27619878e-001],
       [-4.60156725e-134,  8.33235842e-002]])

In [357]:
print(U[:,:l])

[[-0.51952884 -0.27485329]
 [-0.46519818 -0.17909635]
 [-0.41086752 -0.08333941]
 [-0.35653686  0.01241753]
 [-0.3022062   0.10817447]
 [-0.24787554  0.20393141]
 [-0.19354488  0.29968835]
 [-0.13921422  0.39544529]
 [-0.08488356  0.49120223]
 [-0.0305529   0.58695917]]


In [190]:
print(U[:,0].T.dot(U[:,1]))
print(U[:,0].T.dot(U[:,0]))

-1.214306433183765e-16
0.9999999999999993


In [191]:
S[:l]
V[:l]

array([[-0.33721994, -0.33249014, -0.32776033, -0.32303052, -0.31830072,
        -0.31357091, -0.3088411 , -0.3041113 , -0.29938149, -0.29465169],
       [ 0.48139096,  0.37139623,  0.2614015 ,  0.15140676,  0.04141203,
        -0.0685827 , -0.17857743, -0.28857216, -0.3985669 , -0.50856163]])

### algorithm for orthonormal NMF

In [ ]:
[U,S,V] =psvd(A,k)
W(:,1) =sqrt(S(1,1))∗U(:,1) and 
H(1,:) =sqrt(S(1,1))∗V(:,1)' 
for j in range(2,k): 
    3.x=U(:,j);
        y=V(:,j);
    4.x p=pos(x);
        xn=neg(x);
        y p=pos(y);
        yn=neg(y);
    5.x pnrm=norm(x p);
        ypnrm=norm(yp);
        mp=xpnrm*ypnrm;
    6.xnnrm=norm(xn);
        ynnrm=norm(yn);
        mn=xnnrm*ynnrm;
    7.if mp>mn:
            u=x p/xpnrm;
            v=yp/ypnrm;
            sigma=mp;
        else
            u=xn/xnnrm;
            v=yn/ynnrm;
            sigma=mn;
    8.W(:,j)=sqrt(S(j,j)*sigma)*u  
        H(j,:)=sqrt(S(j,j)∗sigma)∗v'

In [14]:
W = np.random.uniform(size=(10,5))
Q,R = np.linalg.qr(W,mode='complete')
Q.shape, R.shape, Q[:,:5], Q[:,5:], R

((10, 10),
 (10, 5),
 array([[-3.65678305e-01, -1.19054026e-01,  2.73671932e-01,
          1.51252901e-02,  6.22191621e-02],
        [-2.16018431e-01, -3.64573047e-01, -2.65867061e-01,
         -1.37290619e-01, -2.53521456e-01],
        [-3.65071066e-01,  2.82124611e-01, -1.94685646e-01,
         -9.14122360e-02, -3.13954098e-02],
        [-1.48981778e-01, -5.48583662e-01,  2.48347771e-01,
         -2.33791512e-01, -2.65770298e-04],
        [-4.66417529e-02, -3.69640244e-02, -6.55204170e-01,
         -1.53934117e-01, -5.15728646e-01],
        [-3.35003659e-01,  2.37602203e-01, -2.74437328e-01,
         -3.30778013e-01,  5.31866421e-01],
        [-1.38312462e-01, -3.05636511e-01,  1.69088332e-01,
         -5.72530317e-01, -1.17820415e-02],
        [-3.51301459e-02, -5.46788678e-01, -4.03839066e-01,
          4.96802054e-01,  4.42908683e-01],
        [-5.50913117e-01,  2.73892616e-02,  2.36045444e-01,
          4.56414232e-01, -3.87935463e-01],
        [-4.75258172e-01,  1.46326510e-01, 

## mapping

let $y_t$ be an $n$-dimensional vector in task (output) space at time $t$ and $m_t$ be an $m$-dimensional muscle activation vector at time $t$ such that $m>n$, there are more electrodes than output dimensions. The mapping from electrodes to output is redundant and noninvertible.

If we assume that the rows of the mapping from electrode to task space $M$ are orthonormal such that:

$$
\begin{align}
M_{n\times m}M_{m\times n}^T=\mathbf{I_{n\times n}}
\end{align}
$$

By constraining the mapping between task and electrode space $M$ to be orthonormal, this mapping won't scale the input variables

$$
\begin{align}
M &= U_{n\times n}\Sigma_{n\times m} V_{m\times m} \\
 &= 
\begin{bmatrix}
- v_1 - \\ 
\vdots \\
- v_n -
\end{bmatrix}
\end{align}
$$

# notes on covariance matrices (for multivariate time series)

In general, the covariance matrix is the representation of the quadratic form $\textrm{var}{\langle\beta,\mathbf{X}\rangle}$:

\begin{align}
\textrm{var} \langle \beta, X\rangle &= var \sum_{i=1}^d \beta_i X_i \\
&=  \sum_{i=1}^d \sum_{j=1}^d \beta_i  \beta_j
cov( X_i ,X_j) \\
&=  \sum_{i=1}^d \sum_{j=1}^d \beta_i  \beta_j
\Sigma_{i,j} \\
&=  \beta^T\Sigma\beta \\
\end{align}

> All covariance matrices are positive definite and all positive definite matrices are the covariance matrix of some multivariate distribution. The sample covariance matrix is singular when there is collinearity between variables or when the number of observations is less than the number of variables.



If we picture a normal distribution, $\Sigma$ is the variance of each variable, and the quadratic form is the measure of how the variables in $\beta$ covary with those in X. Each of the variables in $\beta$ are scaled by the variance of those variables in the distribution induced by the covariance of $\mathbf{X}$. 

## EMG data 

$\mathbf{X}$ is an $m\times t$ data matrix where $m$ is the number of electrodes or muscles, and $t$ is the number of time-ordered samples. $XX^T$ is thus the spatial covariance matrix. The sample spatial covariance is the average over time of the covariance between each electrode channel. Each element $(i,j)$ is the covaraiance of channel $i$ and channel $j$ averaged over all time points.

The sample temporal covariance matrix $X^TX$ is the average over channels of the covariance between each time point. Each element $(i,j)$ in the $t\times t$ matrix is the covariance between time point $i$ and $j$ over all channels.  

$$
\begin{align}
C_{t,{m\times m}} &= X_tX_t^T \,\, \textrm{for} \,\, X_t \in \mathbf{X} \in \mathbb{R}^{+}_{m\times t} \\
\mathbf{C}_{m\times m} & = \frac{1}{t-1}\Sigma_{t=1}^T X_tX_t^T = \mathbf{X}\mathbf{X}^T
\end{align}
$$

Denote the $i$th column of $X$ by $x_i$ and let let $\hat{x_i}$ denote the projection of $x_i$ on  space spanned by $\{x_j : j \neq i \}$. Call $\epsilon_i = x_i - \hat{x_i}.$ Not that if any $\|\epsilon_i\|$ is "small", it suggests strong linear dependence among the columns of $X$

One can prove the $ij$th element of $(X^TX)^{-1}$ is $$\dfrac{\epsilon_i^T\epsilon_j}{\|\epsilon_i\|^2\|\epsilon_j\|^2}.$$

# orthogonal matrices

Orthogonal matrices correspond to linear transformations that preserve the length of vectors (isometries). And the composition of two isometries 𝐹 and 𝐺 is obviously also an isometry.

The product of square orthogonal matrices is orthogonal:

$$\begin{align}
A A^T &= I \\
B B^T &= I \\
(A B)(A B)^T &= ABB^TA^T
&= I\\
\end{align}$$

if
$$
\begin{equation}
XX^T = I
\end{equation}
$$
then
$$
\begin{align}
X &= U\Sigma V^T \\
X &= U\\
\end{align}
$$

For rectangular matrices where $m>n$, those with orthonormal columns:

$$
\begin{align*}
Q^TQ_{m\times n} = \mathbb{I}
\end{align*}
$$

and those with orthonormal rows:

$$
\begin{align*}
QQ^T = \mathbb{I}
\end{align*}
$$

In [ ]:
# Generating orthogonal matrices using QR

import numpy as np
m = 10
n = 2
a = np.random.normal(0,1,size=(m, m))
u = np.random.normal(0,1,size=(n, n))
u = np.linalg.qr(u)[0]
# throw away extra columns
a = np.linalg.qr(a)[0][:,:n].T
# a has orthonormal rows
print(a.shape,u.shape)
print("AA^T", a.dot(a.T))
# u has orthonormal columns and rows
print("UU^T",u.dot(u.T))
print("U^TU",u.T.dot(u))
print("u norm columns",np.linalg.norm(u,axis=0))
print("u norm rows",np.linalg.norm(u,axis=1))
print("a norm rows",np.linalg.norm(a,axis=1))

# Product of two orthogonal matrices is orthogonal, but pay attention to column or row othogonality. 

uprime = a.T.dot(u)
print(uprime.shape)
print(np.linalg.norm(uprime,axis=0))

vprime = u.T.dot(a)
print(vprime.shape)
print(np.linalg.norm(vprime,axis=1))

u,s,v = np.linalg.svd(a)
s = np.pad(np.diag(s),((0,0),(0,8)))
r = u.dot(s).dot(v)
print(u.shape,s.shape,v.shape,r.shape)

u,s

s.dot(v)

v[:2]