In [1]:
import sys
if not '..' in sys.path:
    sys.path.append('..')

from pathlib import Path
from analysis import files, analysis, collection
import numpy as np
from scipy.spatial import distance
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit

%matplotlib inline

In [2]:
from pathlib import Path

ROOT_RAWDATA_PATH = Path("/Users/spencer/motor-control/data/rawdata/")
ROOT_METADATA_PATH = Path("/Users/spencer/motor-control/data/metadata/")

collection_name = "emg_olympics"
subject_name = "peterv"
task_name = "center_hold"
session_name = "session_1"

In [3]:
len(list(x.stem for x in (ROOT_RAWDATA_PATH / collection_name).iterdir() if not "DS_Store" in x.name))
# list(ROOT_METADATA_PATH.iterdir())

46

In [4]:
[p.stem for p in (ROOT_RAWDATA_PATH / collection_name / subject_name).iterdir() if not "DS_Store" in p.name]

['calibration_bars', 'natural_movement', 'center_hold']

In [5]:
directory = ROOT_RAWDATA_PATH / collection_name / subject_name / task_name / session_name
prefix = f"{ROOT_RAWDATA_PATH / collection_name / subject_name / task_name / session_name}/session_result_"

fcount = [f for f in directory.iterdir() if str(f).startswith(prefix)]
print(fcount[0])

/Users/spencer/motor-control/data/rawdata/emg_olympics/peterv/center_hold/session_1/session_result_2021-10-04T19_51_36.csv


In [6]:
directory = ROOT_RAWDATA_PATH / collection_name / subject_name / task_name / session_name
prefix = f"{ROOT_RAWDATA_PATH / collection_name / subject_name / task_name / session_name}/session_result"
try:
    outcome_path = [f for f in directory.iterdir() if str(f).startswith(prefix)][0]
    # task_names = [p.stem for p in (ROOT_RAWDATA_PATH / collection_name / task_name / name / session_result_).iterdir() if not "DS_Store" in p.name]
except IndexError:
    raise ValueError(f"No file found with prefix {prefix}") 
behavior = np.genfromtxt(str(outcome_path), delimiter=",", skip_header=1, dtype=None, encoding=None)
print(behavior)

[('Miss', 0.7666667, 5.016667 , -0.87, -0.5 )
 ('Miss', 0.7666667, 5.016667 ,  0.  , -1.  )
 ('Miss', 0.7666667, 5.016667 , -0.5 , -0.87)
 ('Miss', 0.7666667, 5.016667 ,  0.87, -0.5 )
 ('Hit', 0.7666667, 0.8666667,  0.5 ,  0.87)
 ('Miss', 0.7666667, 5.016667 , -0.87,  0.5 )
 ('Miss', 0.95     , 5.016667 ,  0.5 , -0.87)
 ('Miss', 0.7666667, 5.016667 , -1.  ,  0.  )
 ('Hit', 1.116667 , 1.083333 , -0.5 ,  0.87)
 ('Miss', 0.7666667, 5.016667 ,  0.  ,  1.  )
 ('Hit', 2.783333 , 3.633333 ,  1.  ,  0.  )
 ('Hit', 1.066667 , 2.433333 ,  0.87,  0.5 )]


In [7]:
recorded_number = "1"
directory = ROOT_RAWDATA_PATH / collection_name / subject_name / task_name / session_name 
prefix = f"{ROOT_RAWDATA_PATH / collection_name / subject_name / task_name / session_name / recorded_number}_behavior_"
filename_list = [f for f in directory.iterdir() if str(f).startswith(prefix)]
filename_list.sort()
filename_list

[PosixPath('/Users/spencer/motor-control/data/rawdata/emg_olympics/peterv/center_hold/session_1/1_behavior_2021-10-04T19_51_46.csv')]

In [10]:
s = collection.Session(collection_name, subject_name, task_name, "session_1")
print(list(s.trials.values())[0].get_trajectory())

[[1.66672000e-02 9.21776891e-03 3.71582806e-03]
 [1.66672000e-02 1.08617544e-02 3.28379869e-03]
 [1.66672000e-02 1.25864148e-02 2.89471447e-03]
 ...
 [5.75601120e+00 5.84854364e-01 7.10846961e-01]
 [5.77267890e+00 6.00339770e-01 7.22643018e-01]
 [5.77267890e+00 6.15862608e-01 7.32895553e-01]]


In [12]:
no_hold_number = 0
directory = ROOT_RAWDATA_PATH / collection_name / subject_name / task_name / session_name 
prefix = f"{ROOT_RAWDATA_PATH / collection_name / subject_name / task_name / session_name / str(recorded_number)}_emg_2021"
filename_list = [f for f in directory.iterdir() if str(f).startswith(prefix)]
filename_list.sort()
fname = filename_list[no_hold_number]